# Generated by Django 4.2.25 on 2025-11-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_contact_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
