# Generated by Django 4.2.25 on 2025-11-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_gallery_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('sub_header', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_details', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='author_images/')),
                ('author_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
