# Generated by Django 4.2.25 on 2025-11-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_image',
        ),
    ]
