# Generated by Django 4.2.25 on 2025-11-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_comment_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='blog_image',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
