# Generated by Django 4.2.25 on 2025-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_comment_blog_remove_comment_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('second_title', models.CharField(blank=True, max_length=200, null=True)),
                ('second_description', models.TextField(blank=True, null=True)),
                ('attorneys_name', models.CharField(blank=True, max_length=200, null=True)),
                ('attorney_dsescription', models.TextField(blank=True, null=True)),
                ('attorney_position', models.TextField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('attorney_image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('third_title', models.CharField(blank=True, max_length=200, null=True)),
                ('third_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
