# Generated by Django 4.2.25 on 2025-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Clients', max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('client_image', models.ImageField(upload_to='client_logos/')),
                ('client_message', models.TextField(blank=True, null=True)),
                ('practice_area', models.CharField(blank=True, max_length=200, null=True)),
                ('practice_area_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
