# Generated by Django 4.2.25 on 2025-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_attorney'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Welcome to Our Law Firm', max_length=200)),
                ('sub_header', models.TextField()),
                ('image_background', models.ImageField(upload_to='index_images/')),
                ('second_header', models.CharField(blank=True, max_length=200, null=True)),
                ('second_sub_header', models.TextField(blank=True, null=True)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='index_images/')),
            ],
        ),
    ]
