# Generated by Django 4.2.25 on 2025-11-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Practice Areas', max_length=200)),
                ('main_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='practice_area_images/')),
                ('practice_area', models.CharField(max_length=100)),
                ('practice_area_description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='practice_icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='PracticeArea',
        ),
    ]
