# Generated by Django 4.2.25 on 2025-11-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_oldpracticearea_delete_practicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAreaMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Practice Areas', max_length=200)),
                ('main_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='practice_area_images/')),
                ('practice_area', models.CharField(max_length=100)),
                ('practice_area_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='practice_icons/')),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='apps.practiceareamain')),
            ],
        ),
        migrations.DeleteModel(
            name='OldPracticeArea',
        ),
    ]
