# Generated by Django 4.2.25 on 2025-11-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_practiceareamain_practiceservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceservice',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='apps.practiceareamain'),
        ),
    ]
