# Generated by Django 4.2.25 on 2025-11-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_practiceservice_main_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image_background',
        ),
        migrations.CreateModel(
            name='IndexBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='index_images/')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_images', to='apps.index')),
            ],
        ),
    ]
