# Generated by Django 4.2.25 on 2025-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_freelegaladvice_legaladviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_details', models.TextField()),
                ('service_1', models.CharField(max_length=200)),
                ('service_2', models.CharField(max_length=200)),
                ('service_3', models.CharField(max_length=200)),
                ('service_4', models.CharField(max_length=200)),
                ('service_5', models.CharField(max_length=200)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('org_logo', models.ImageField(upload_to='organization_logos/')),
            ],
        ),
    ]
