# Generated by Django 4.2.25 on 2025-11-13 06:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_organizationinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceservice',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
