# Generated by Django 4.2.25 on 2025-11-13 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_blog_description_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='item_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
